# Generated by Django 4.1 on 2022-09-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='estudios',
            name='año_comienzo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='año_finalizacion',
            field=models.DateField(),
        ),
    ]
